# Generated by Django 5.1.6 on 2025-02-23 15:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtistProfile',
            new_name='UserProfile',
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
    ]
