# Generated by Django 4.1 on 2025-02-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_user_portfolioimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
