# Generated by Django 4.1 on 2025-03-02 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_userprofile_social_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artworks/')),
                ('title', models.CharField(max_length=255, verbose_name='Название работы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Продано')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks_for_sale', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
