# Generated by Django 4.2.20 on 2025-03-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_artworkforsale_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkforsale',
            name='category',
            field=models.CharField(choices=[('Популярное', 'Популярное'), ('Природа', 'Природа'), ('Абстракция', 'Абстракция'), ('Аниме', 'Аниме'), ('Оригинальные персонажи', 'Оригинальные персонажи'), ('Фан-Арт', 'Фан-Арт')], default='featured', max_length=40, verbose_name='Категория'),
        ),
    ]
