# Generated by Django 4.2.20 on 2025-03-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_artworkforsale_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст правил')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Правило платформы',
                'verbose_name_plural': 'Правила платформы',
            },
        ),
    ]
