# Generated by Django 4.2.20 on 2025-04-23 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0019_artworkcomment_commentlike_delete_artworkreview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='artworkcomment',
            name='attachment',
        ),
        migrations.AddField(
            model_name='artworkcomment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comment_attachments/'),
        ),
        migrations.AddField(
            model_name='artworkcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_artwork_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='users.artworkcomment'),
        ),
    ]
