# Generated by Django 4.2.20 on 2025-04-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_commentlike_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkcomment',
            name='likes',
        ),
        migrations.AlterField(
            model_name='artworkcomment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comments/'),
        ),
    ]
