# Generated by Django 4.2.20 on 2025-04-23 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0021_remove_artworkcomment_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_artwork_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
